### PR TITLE
port to python 38

### PR DESCRIPTION
**Pull request by bissenbay**
Related-To: https://github.com/thoth-station/thoth-application/issues/545

### CODE REVIEW

**Comment by bissenbay** [comment]
@fridex @harshad16 locally when I run `/usr/local/bin/pipenv run python setup.py test` tests pass, it is not passing here, why?

**Comment by fridex** [comment]
> @fridex @harshad16 locally when I run `/usr/local/bin/pipenv run python setup.py test` tests pass, it is not passing here, why?

It looks like tests are running Python 3.6 instead of Python 3.8.

**Comment by bissenbay** [comment]
> > @fridex @harshad16 locally when I run `/usr/local/bin/pipenv run python setup.py test` tests pass, it is not passing here, why?
> 
> It looks like tests are running Python 3.6 instead of Python 3.8.

From what you are saying, I understand that tests are running on python 3.6 on the `ci run`, right? So, ss there a way to test it on python 3.8? Should I make an adjustment, so it runs on `py 3.8`?

**Comment by harshad16** [comment]
@bissenbay  can you please add the file `.aicoe-ci.yaml` in this repository to handle the pytest issue.

```
check:
  - thoth-build
  - thoth-pytest-py38
release:
  - upload-pypi-sesheta
build:
  base-image: quay.io/thoth-station/s2i-thoth-ubi8-py38:latest
  build-stratergy: Source
  registry: quay.io
  registry-org: thoth-station
  registry-project: buildlog-parser
  registry-secret: thoth-station-thoth-pusher-secret
```

**Comment by bissenbay** [comment]
> @bissenbay can you please add the file `.aicoe-ci.yaml` in this repository to handle the pytest issue.
> 
> ```
> check:
>   - thoth-build
>   - thoth-pytest-py38
> release:
>   - upload-pypi-sesheta
> build:
>   base-image: quay.io/thoth-station/s2i-thoth-ubi8-py38:latest
>   build-stratergy: Source
>   registry: quay.io
>   registry-org: thoth-station
>   registry-project: buildlog-parser
>   registry-secret: thoth-station-thoth-pusher-secret
> ```

sure, thanks @harshad16

**Comment by bissenbay** [comment]
@fridex @harshad16 this is also locally passes, how I should change, so it tests on `py 3.8`?
```
➜  buildlog-parser git:(port-to-py38) /usr/local/bin/pipenv run python setup.py test
running test
WARNING: Testing via this command is deprecated and will be removed in a future version. Users looking for a generic test entry point independent of test runner are encouraged to use tox.
running egg_info
writing thoth_buildlog_parser.egg-info/PKG-INFO
writing dependency_links to thoth_buildlog_parser.egg-info/dependency_links.txt
writing entry points to thoth_buildlog_parser.egg-info/entry_points.txt
writing requirements to thoth_buildlog_parser.egg-info/requires.txt
writing top-level names to thoth_buildlog_parser.egg-info/top_level.txt
reading manifest file 'thoth_buildlog_parser.egg-info/SOURCES.txt'
writing manifest file 'thoth_buildlog_parser.egg-info/SOURCES.txt'
running build_ext
========================================================================================== test session starts ==========================================================================================
platform linux -- Python 3.8.5, pytest-6.1.2, py-1.9.0, pluggy-0.13.1 -- /home/bdauletb/.local/share/virtualenvs/buildlog-parser-yktkG2xF/bin/python
cachedir: .pytest_cache
rootdir: /home/bdauletb/Documents/thoth/buildlog-parser
plugins: mypy-0.8.0, timeout-1.4.2
timeout: 60.0s
timeout method: signal
timeout func_only: False
collected 7 items                                                                                                                                                                                       

thoth/buildlog_parser/__init__.py::mypy PASSED
thoth/buildlog_parser/__init__.py::mypy-status PASSED
thoth/buildlog_parser/cli.py::mypy PASSED
thoth/buildlog_parser/exceptions.py::mypy PASSED
thoth/buildlog_parser/parsing.py::mypy PASSED
tests/base.py::mypy PASSED
tests/test_parsing.py::mypy PASSED
================================================================================================= mypy ==================================================================================================

Success: no issues found in 6 source files
=========================================================================================== 7 passed in 0.09s ===========================================================================================
```

**Comment by harshad16** [comment]
pytest would run with python38 once this pr is merged.

**Review by harshad16 — APPROVED** [review]
lgtm

**Review by fridex — APPROVED** [review]
:shipit:

**Pull request merged**
